- name: "{{ container_engine_name }} | Create service systemd directory if it doesn't exist"
  file:
    path: "/etc/systemd/system/{{ container_engine_name }}.service.d"
    state: directory
    mode: 0755

- name: "{{ container_engine_name }} | Write proxy drop-in"
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/{{ container_engine_name }}.service.d/http-proxy.conf
    mode: 0644
  notify: "restart {{ container_engine_name }}"

- name: Flush handlers
  meta: flush_handlers
