---
- include_tasks: test.yaml
  when: testmode == true

- include_tasks: ovpn_connect.yaml
  when: connected == true and testmode == false

- include_tasks: ovpn_disconnect.yaml
  when: connected == false and testmode == false

