---

- include_tasks: singbox_disconnect.yaml

- name: Copy systemd file
  template:
    src: "ssh_tunnel@.service.j2"
    dest: "/etc/systemd/system/ssh_tunnel@.service"
    mode: 0644
  check_mode: "{{ checkmode }}"

- name: Copy config file
  template:
    src: "ssh_tunnel@main.j2"
    dest: "/etc/default/ssh_tunnel@main"
    mode: 0644
  check_mode: "{{ checkmode }}"

- name: Enable and start singbox service
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    daemon_reload: true
    name: ssh_tunnel@main.service
  check_mode: "{{ checkmode }}"

- name: env_proxy connect
  include_role:
    name: "hadi2f244.free_me.env_proxy"
  vars:
    connected: true
    http_proxy: "http://127.0.0.1:{{proxy_port}}"
    https_proxy: "http://127.0.0.1:{{proxy_port}}"
  when: set_env_proxy == true

- name: apt_proxy connect
  include_role:
    name: "hadi2f244.free_me.apt_proxy"
  vars:
    connected: true
    http_proxy: "http://127.0.0.1:{{proxy_port}}"
    https_proxy: "http://127.0.0.1:{{proxy_port}}"
  when: set_apt_proxy == true

- name: container_proxy connect
  include_role:
    name: "hadi2f244.free_me.container_proxy"
  vars:
    connected: true
    http_proxy: "http://127.0.0.1:{{proxy_port}}"
    https_proxy: "http://127.0.0.1:{{proxy_port}}"
  when: set_container_proxy == true