---
- name: restart docker
  command: /bin/true
  notify:
    - Docker | reload systemd
    - Docker | reload docker.socket
    - Docker | reload docker
    - Docker | wait for docker

- name: Docker | reload systemd
  systemd:
    name: docker
    daemon_reload: true
    masked: no

- name: Docker | reload docker.socket
  service:
    name: docker.socket
    state: restarted
  when: ansible_os_family in ['Flatcar', 'Flatcar Container Linux by Kinvolk']

- name: Docker | reload docker
  service:
    name: docker
    state: restarted

- name: Docker | wait for docker
  command: "docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0


- name: restart containerd
  command: /bin/true
  notify:
    - Containerd | restart containerd
    - Containerd | wait for containerd

- name: Containerd | restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes
    masked: no

- name: Containerd | wait for containerd
  command: "/usr/bin/ctr images ls -q"
  register: containerd_ready
  retries: 8
  delay: 4
  until: containerd_ready.rc == 0

- name: restart crio
  command: /bin/true
  notify:
    - CRI-O | reload systemd
    - CRI-O | reload crio

- name: CRI-O | reload systemd
  systemd:
    daemon_reload: true

- name: CRI-O | reload crio
  service:
    name: crio
    state: restarted
    enabled: yes
