---

- include_tasks: test.yaml
  when: testmode == true

- include_tasks: apt_proxy_connect.yaml
  when: connected == true and testmode == false

- include_tasks: apt_proxy_disconnect.yaml
  when: connected == false and testmode == false